### ISSUE TITLE
おすすめのツールを列挙する

### ISSUE THREAD

**Issue by KATO-Hiro** [KATO-Hiro/AtCoderClans#1961]
## WHY

+ 掲載させていただいているツールが増加したことで，初見の利用者の選択コストが増加している
+ minmumなセットを提供することで，ツールを導入しないことによるコンテスト参戦のハンディを減らす

## WHAT

+ 70〜80%程度のユーザが導入して便利だと思えるようなツールを紹介
  + 多くても10種類程度（人の認知負荷は7±2）
  + For Beginnersへの導線も用意する
+ 代替ツールやカスタマイズなどの高度な利用法がある場合については，関連リンクに飛んでもらうようにする

+ 選択の基準
  + 想定ユーザ
    + サービス・ツールの導入を考えているが、Clansからその人にとって必要なもの選択するのが難しく、断念している
    + レーティング帯だと、灰色から茶色（ツールに関心がない場合は、緑下位）くらい
  + 導入が比較的簡単
  + サービス・ツールを利用したときに、メリットが著しく大きい(Perf・Ratingの上昇に寄与する可能性が高い) 
  + 利用しているユーザが多い
  + 一度利用すると、そのありがたみがよく分かる、いぶし銀なツール
  + For Beginnersでは、紹介しきれなかったサービス・ツール
  + 他のユーザとの比較よりも、過去の自分と比較できるツールを優先的に（最初の挫折率を下げることの方が大事）

## TODO

- [x] 紹介するツールを10種類程度まで絞る
- [x] For Beginnersへの導線を用意する
- [x] ページの概要・狙いを記載する
- [ ] 他のページへの導線を考える

### 問題を効率よく解くための補助ツール

- [x] AtCoderResultNotifier: 数秒でもあるとないとでは違う。
- [x] AtCoder_submit_keyboard_shortcut: 同上。
- [x] AtCoder Submission Status: 一覧でジャッジ結果が表示されるのは大事。
- [x] Comfortable Atcoder: あることが前提になっているツール。多機能。Chromeの利用が前提。

### 過去問を解く

- [x] AtCoder Difficulty Display: テキトーに開いたときに、問題のdiffを知りたいとき用。
- [x] AtCoder Tags: 特定のカテゴリを集中的に学習したいときにオススメ。

### 手元でテストする

- [x] AtCoder Easy Test: 競技プログラミングに参加する人は、テストをするようになって欲しい。Advancedとして、CLIツールへの導線も用意する。

### コンテストを振り返る

- [x] AtCoder TL: 色別のTL。解法の参考になる&お祭り。

### UIを見やすくするツール

- [x] AtCoderPerformanceColorizer: 成績の視認性を高める上では必須。
- [x] AtCoder Submission User Colorizer: 提出コードを見るかどうかの判断材料に
- [x] atcoder-tasks-page-colorizer: Problemsを見に行かなくても、回答状況が分かる

**Comment by KATO-Hiro** [comment]
### 優先度: 低

- [ ] PROCON Q&A  - もっと活用されてもいいサービス(Clansが誕生したのは、同サービスをもっと利用して欲しいというのが理由の一つだったりする)なのに、利用している人が少ない気がする。

**Comment by KATO-Hiro** [comment]
### 優先度: 中

- [ ] AtCoder Scores: 得点別のリストは、Problemsにも実装されている。精進グラフを見たいときに利用することが多そう
- [ ] GRAPH × GRAPH: グラフの問題を解く上では、ほぼ必須。ただ、最初に導入するツールとしては、時期尚早という印象がある。
- [ ] AtCoder Auto Pager
- [ ] AtCoder平均 
- [ ] Atcoder Beginner Contest Tournament: ABCに参加するモチベーションにつながるサービス。
- [ ] AtCoderFacts: 各種統計情報が掲載されている
- [ ] AtCoder Hot Problems: Problemsの次に紹介したいツール
- [ ] AtCoder Rivals: 競争心とメンタルの強いユーザならオススメ
- [ ] 競プロer Bot: 多機能ゆえに、最初に導入するにはやや情報量が多いか?

**Comment by KATO-Hiro** [comment]
### For Beginnersで掲載済み

ただし、ユーザによってはFor Beginnersを見ない可能性も高いので、悩みどころ

- [ ] AtCoder Problems
- [ ] CLIST
- [ ] 競プロリマインダー 
- [ ] AtCoder TestCase Extension
- [ ] 競プロer集会所
- [ ] ac-predictor
- [ ] AtCoder Rating Simulator 
- [ ] AtCoder Easy Test
