### ISSUE TITLE
サイトジェネレータ: Material for MkDocsを導入

### ISSUE THREAD

**Issue by KATO-Hiro** [KATO-Hiro/AtCoderClans#3787]
## WHY

- 現在はデフォルトのJekyllを使用している
- △掲載数が増えてきたので、見やすさ・表示速度の低下に課題を感じている
  - 情報量が多いので、初見の人には辛いかも 
- ローカルで見た目のチェックを事前にしたい
- △: Google検索を導入しているが、探しづらい
- △: 掲載数の増加に対して、カテゴリ分けを行いページを分割することで対処してきたが、そろそろ限界ではないかと思っている

- 置き換えの理由
  - 別ブロジェクトで導入しつつある
    - サイトの更新がより楽に
    - 閲覧しやすい 
  - ymlファイルを用意すれば、実施的にmarkdownを書くことに集中できる
  - 検索機能がデフォルトで強い 

## TODO

- [x] ローカルで環境構築
- [x] 現時点で重いページを対象に動作確認してみる
  - [x] cli
  - [x] libraries
  - [x] article and books 
- [x] docs/にページを追加
- [x] 各ページに対象読者を追加
- [x] カテゴリを再編 // 暫定版です。変更の可能性があります。
  - [x] ホームページ
  - [x] 各ページの概要
  - [x] 初心者向け
    - [x] Q1
    - [x] Q2
    - [x] Q3
    - [x] Q4
    - [x] Q5
    - [x] Q6
    - [x] Q7
    - [x] Q8 
  - [x] おすすめサービス・ツール
  - [x] Webアプリ、Webサイト
    - [x] Webアプリ、Webサイト
      - [x] はじめに 
      - [x] 問題を解く
      - [x] 問題を解くための補助ツール
      - [x] コンテスト予定を確認
      - [x] 成績を見る
      - [x] 成績に関する派生サービス
      - [x] 統計情報
      - [x] クイズ・ゲームなど
      - [x] その他 // 廃止。他のページに再分類したため。
    - [x] Bot
    - [x] Web API 
    - [x] その他
  - [x] スクリプト
    - [x] ユーザスクリプト
      - [x] コンテストに参加
      - [x] 成績を表示
      - [x] 自動通知 // コードの提出・確認を簡単に　へ移行 
      - [x] ショートカット // 問題を解く & コードの提出・確認を簡単に　へ移行 
      - [x] 色付け
      - [x] 表示の改善 // 再編により廃止
      - [x] 問題を解く
      - [x] コードの提出・確認を簡単に
      - [x] 解説を読む
      - [x] ライバルを探す・競う
      - [x] 便利な機能の追加 // 再編により廃止
        - [x] タブ
        - [x] ボタン
        - [x] リンク
        - [x] 未分類
      - [x] ネタ  
      - [x] 開発者向けの情報
    - [x] Chrome拡張 // 他のページに合わせて再編
      - [x]  問題を解く
      - [x] コードの提出・確認
      - [x] 復習
      - [x] コンテストに参加
      - [x] 成績を見る
      - [x] UIの改善 
  - [x] コマンドラインツール
     - [x] テストツール
     - [x] テンプレート
     - [x] 専用言語
     - [x] ソルバー
     - [x] バックアップ
     - [x] 作問支援ツール 
     - [x] 未分類
  - [x] ライブラリ・スニペット
    - [x] ACL
    - [x] ACLの解説資料
    - [x] ライブラリチェッカー
    - [x] 有志による公開ライブラリ
  - [x] 記事・書籍
    - [x] 記事
      - [x] 入門者・初心者向け
      - [x] 環境構築
      - [x] プログラミング言語を学ぶ
      - [x] アルゴリズムを学ぶ
      - [x] 数学を学ぶ
      - [x] ヒューリスティック問題を解く
      - [x] コードを実装する上での工夫
      - [x] 解説ブログ
      - [x] 練習方法
      - [x] 成績を見る
      - [x] 難問へのアプローチ方法
      - [x] 問題作成の準備
      - [x] PAST
      - [x] 1年の振り返り
      - [x] 部活・サークル・同好会
      - [x] 開発に関心がある人向け 
      - [x] 未分類
    - [x] ブログ
      - [x] アルゴリズム部門
      - [x] ヒューリスティック部門
    - [x] 資料集
    - [x] 書籍
    - [x] SNS
  - [x] 動画
    - [x] YouTube
    - [x] ニコニコ動画
    - [x] 番組アーカイブ
  - [x] 色変記事
    - [x] 茶
    - [x] 緑
    - [x] 水
    - [x] 青
    - [x] 黄
    - [x] 橙
    - [x] 赤
    - [x] 引退 
  - [x] 関連コンテストサイト
     - [x] アルゴリズム系
       - [x] AOJ 
     - [x] 数学系
     - [x] パズル系
     - [x] DB系
     - [x] Webサービス系
     - [x] セキュリティ系
  - [x] アーカイブ
    - [x] 追加確認が必要
    - [x] 情報が古くなっている
    - [x] リンク切れの可能性が高い
    - [x] サービス終了
  - [x] 連絡先
  - [x] プライバシーポリシー
  - [x] スペシャルサンクス
  - [x] 開発者向け情報
    - [x] ライセンス
    - [x] コントリビューションの方法
    - [x] 設計方針
    - [x] CHANGELOG
- [x] 上記に伴ってリンクが壊れた場合への対処
- [x] Deploy前のアナウンス（Homeページ以外をブックマークしているユーザには再登録のお願い）
- [x] ユーザへのアンケートを実施

**Comment by KATO-Hiro** [comment]
## WHAT

- 運用しながら、ダウンタイムを極小にしてジェネレータの置き換え
  - 月間で約900〜1400人が利用してくださっている
  - リンクが切れている状態を短くしたい
- リプレースに合わせて、ページの再構成・カテゴリの見直しも徐々に進めたい

**Comment by KATO-Hiro** [comment]
## 改善ポイント

- 検索性の改善（デフォルト）
- 表示速度の改善
- 1ページあたりの表示数を減らす
- 閲覧しやすく、欲しい情報がすぐに見られるように
- 情報の粒度の調整 
  - 重要度が高い、汎用性の高い情報を先頭に
  - 高難易度やマニアックな内容はやや後ろに(advanced)

**Comment by KATO-Hiro** [comment]
## 懸念材料

- リプレースにどれぐらいの工数がかかりそうか?
  - 必要な作業を列挙 & ローカルで少し作業してみる
- ユーザがリプレースそのものを望んているのか?

**Comment by KATO-Hiro** [comment]
リストの参考情報

https://zenn.dev/yutakatay/articles/neovim-pluginlist
https://github.com/yutkat/my-neovim-pluginlist

**Comment by KATO-Hiro** [comment]
## Homeのページ紹介

- カテゴリ分け
  - はじめての方へ
  - 便利なサービス・ツールを探す
  - 新しい知識を身につける or 学ぶ
  - その他（作者への連絡・更新履歴・etc）

**Comment by KATO-Hiro** [comment]
## TODO

環境変数を使う

https://github.com/waylan/pyyaml-env-tag
