### ISSUE TITLE
AtCoderの仕様変更によるサービスの稼働状況の調査

### ISSUE THREAD

**Issue by KATO-Hiro** [KATO-Hiro/AtCoderClans#5810]
## WHAT

- サイトの利用者に最新かつ正確な情報を届けるため

## TODO

- [x] atcoder rating simulator: https://atcoder-rating-simulator.dt.r.appspot.com/
- [x] AtCoder Replay: https://twitter.com/kakira9618/status/1651875954078404609
  - [x] 暫定的に復旧 https://twitter.com/kakira9618/status/1652722269322645504
- [ ]
